apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apiserver
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8080
  selector:
    io.kompose.service: {{ .Release.Name }}-apiserver
