apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-apiserver-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /graphql
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
      - {{ .Values.letsencrypt.domain }}
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ .Values.letsencrypt.domain }}
    http:
      paths:
        - path: /graphql
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-apiserver
              port: 
                number: 8081