apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{ .Release.Name }}-processor-tmp-content
  name: {{ .Release.Name }}-processor-tmp-content
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
