apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Release.Name }}-redisgraph
  name: {{ .Release.Name }}-redisgraph
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: {{ .Release.Name }}-redisgraph

