{{- define "rhema.env" }}
- name: BUCKET
  value: "rhema-content"
- name: GOOGLE_APPLICATION_CREDENTIALS
  value: "/gcp-secrets/service-account-file.json"
- name: MQTT_BROKER
  value: "tcp://{{ .Release.Name }}-mqtt:1883"
- name: REDIS_HOST
  value: "{{ .Release.Name }}-redisgraph"
- name: COPY_TMP_TO_LOCAL
  value: "false"
{{- end }}