FROM kai5263499/rhema-builder as builder

COPY / /go/src/github.com/kai5263499/rhema

RUN cd /go/src/github.com/kai5263499/rhema/cmd/scrape && \
    go build && \
    ldd scrape | tr -s '[:blank:]' '\n' | grep '^/' | \
    xargs -I % sh -c 'mkdir -p $(dirname deps%); cp % deps%;'

FROM scratch

LABEL MAINTAINER="Wes Widner <kai5263499@gmail.com>"

ENV MIN_TEXT_BLOCK_SIZE="100"

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/github.com/kai5263499/rhema/cmd/scrape/deps /
COPY --from=builder /go/src/github.com/kai5263499/rhema/cmd/scrape/scrape /scrape

ENTRYPOINT [ "/scrape" ]