services:
  kafka:
    profiles:
    - kafka
    command:
    - redpanda
    - start
    - --check=false
    - --smp
    - "1"
    - --memory
    - 1G
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - "0"
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
    - --set
    - redpanda.auto_create_topics_enabled=true
    - --set
    - redpanda.enable_idempotence=true
    - --set
    - redpanda.enable_transactions=true
    image: docker.vectorized.io/vectorized/redpanda:v22.1.9
    container_name: kafka-1
    healthcheck:
      test: "curl -s -o /dev/null http://localhost:8082/topics || exit 1"
      interval: 10s
      timeout: 3s
      retries: 100
    ports:
    - ${KAFKA_SSL_PORT:-9092}:9092
    - ${KAFKA_PLAINTEXT_PORT:-29092}:29092

  kafka-ui:
    profiles:
      - kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "${KAFKA_UI_PORT:-9000}:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=internal-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
  redpanda-console:
    profiles:
      - redpanda-console
    image: docker.redpanda.com/vectorized/console:latest
    container_name: redpanda-console-1
    environment:
    - KAFKA_BROKERS=kafka-1:9092
    ports:
    - ${KAFKA_UI_PORT:-18080}:8080
    restart: always
    depends_on:
      kafka:
        condition: service_healthy