services:
  redis:
    profiles:
      - redis
    image: redis:alpine3.16
    container_name: redis-1
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "${REDIS_PORT:-6379}:6379"
    expose:
      - 6379
