version: '3'
services:
  processor:
    environment: 
      - KAFKA_BROKERS=tcp://mqtt:1883
      - REDIS_HOST=redis-1
    restart: always
    volumes: 
      - tmp-content:/tmp
    image: "kai5263499/rhema-processor:latest"
    build: 
      context: .
      dockerfile: cmd/processor/Dockerfile
  apiserver:
    environment: 
      - MQTT_BROKER=tcp://mqtt:1883
      - REDIS_HOST=redis-1
    restart: always
    image: "kai5263499/rhema-apiserver:latest"
    ports:
      - "8081:8080"
    build:
      context: .
      dockerfile: cmd/apiserver/Dockerfile
  contentbot:
     environment: 
       - MQTT_BROKER=tcp://mqtt:1883
       - SLACK_TOKEN=${SLACK_TOKEN}
       - CHANNELS
     restart: always
     image: "kai5263499/rhema-bot:latest"
     build:
       context: .
       dockerfile: cmd/contentbot/Dockerfile
