name: rhema
description: A generated Helm Chart for rhema
version: 0.0.9
apiVersion: v1
keywords:
  - rhema
sources:
home:
dependencies:
  - name: "emqx"
    repository: "https://repos.emqx.io/charts"
    version: "4.2.8"

