openapi: "3.0.0"
info:
  version: 1.0.0
  title: rhemaapi
  description: Manage rhema assets
servers:
  - url: //localhost:8080/v1
  - url: //host.docker.internal:8080/v1
paths:
  /:
    get:
      tags: [v1]
      operationId: Ping
      description: Required by agent 
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
                example: OK
  /live:
    get:
      tags: [v1]
      operationId: Live
      description: K8 Liviness
      responses:
        default:
          $ref: "#/components/responses/Liveness"
  /ready:
    get:
      tags: [v1]
      operationId: Ready
      description: K8 Readiness
      responses:
        default:
          $ref: "#/components/responses/Readiness"
  /request:
    post:
      tags: [v1]
      operationId: SubmitRequest
      parameters:
        - name: X-Forwarded-For
          in: header
          description: Forwarded by haproxy
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/SubmitRequestInput"
      responses:
        202:
          $ref: "#/components/responses/SubmitRequestOutput"
          description: Accepted content request for processing
  /status/{request_id}:
    get:
      tags: [v1]
      operationId: RetrieveResultStatus
      parameters:
        - name: request_id
          in: path
          schema:
            type: string
            description: uuidv4
            pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
            example: c73bcdcc-2669-4bf6-81d3-e4ae73fb11fd
      responses:
        200:
          $ref: "#/components/responses/SubmitRequestOutput"
          description: Latest submited request output
        404:
          description: Request hash not found
  /result/{type}/{request_id}:
    get:
      tags: [v1]
      operationId: RetrieveResultContent
      parameters:
        - name: request_id
          in: path
          schema:
            type: string
            description: uuidv4
            pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
            example: c73bcdcc-2669-4bf6-81d3-e4ae73fb11fd
        - name: type
          in: path
          schema:
            type: string
            description: content type
            pattern: ^(URI|YOUTUBE|TEXT|AUDIO|VIDEO|PDF|YOUTUBE_LIST)$
            example: AUDIO
      responses:
        200:
          description: Binary result of processed request
          $ref: "#/components/responses/Binary"
        500:
          description: Internal Error
  /list-requests:
    get:
      tags: [v1]
      operationId: ListAllRequests
      responses:
        200:
          $ref: "#/components/responses/SubmitRequestOutput"
          description: List of all submitted requests found in boltdb
components:
  schemas:
    Status:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Status Code
        message:
          type: string
          description: Status Message
    Liveness:
      required:
      - health
      - real_ip
      properties:
        health:
          type: string
        real_ip:
          type: string
    Readiness:
      required:
      - health
      - real_ip
      properties:
        health:
          $ref: "#/components/schemas/Health"
        real_ip:
          type: string
    Health:
      description: https://github.com/gritzkoo/golang-health-checker
      required:
      - status
      - date
      - duration
      - integrations
      properties:
        name:
          type: string
        status:
          type: boolean
        version:
          type: string
        date:
          type: string
        duration:
          x-go-type: float64
        integrations:
          type: array
          items:
            $ref: "#/components/schemas/HealthCheck"
    HealthCheck:
      required:
      - name
      - kind
      - status
      - response_time
      - url
      properties:
        name:
          type: string
        kind:
          type: string
        status:
          type: boolean
        response_time:
          x-go-type: float64
        url:
          type: string
          format: uri
        errors:
          x-go-type: error
    SubmitRequestInput:
      required:
        - uri
      properties:
        type:
          type: string
          pattern: ^(URI|YOUTUBE|TEXT|AUDIO|VIDEO|PDF|YOUTUBE_LIST)$
        request_hash:
          type: string
        text:
          type: string
        title:
          type: string
        created:
          type: integer
          format: uint64
        size:
          type: integer
          format: uint64
        length:
          type: integer
          format: uint64
        uri:
          type: string
        submitted_by:
          type: string
        submitted_at:
          type: integer
        number_of_conversions:
          type: integer
          format: uint32
        download_uri:
          type: string
        words_per_minute:
          type: integer
          format: uint32
        espeak_voice:
          type: string
        atempo:
          type: string
        submitted_with:
          type: string
        storage_path:
          type: string
  requestBodies:
  responses:
    Liveness:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Liveness"
    Readiness:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Readiness"
    SubmitRequestOutput:
      content:
        application/json:
          type: array
          schema:
            $ref: "#/components/schemas/SubmitRequestInput"
    Binary:
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary